export const INFERNAL_HOUND_CONFIG = {
  texture: 'infernal-hound-placeholder',
  maxHealth: 85,
  aggroRadius: 680,
  bodyWidth: 68,
  bodyHeight: 34,
  prowlSpeed: 150,
  warningDuration: 650,
  chargeSpeed: 820,
  maxChargeDuration: 1_000,
  stunDuration: 700,
  attackCooldown: 1_450,
  chargeDamage: 20,
  trailInterval: 90,
  trailLifetime: 1_000,
  trailDamage: 4,
  trailDamageCooldown: 400,
} as const;

export const EXECUTIONER_DOLL_CONFIG = {
  texture: 'executioner-doll-placeholder',
  maxHealth: 100,
  aggroRadius: 700,
  bodyWidth: 54,
  bodyHeight: 78,
  hoverSpeed: 230,
  hoverOffset: 190,
  warningDuration: 700,
  slamSpeed: 1_000,
  recoveryDuration: 700,
  attackCooldown: 1_700,
  shockwaveRange: 180,
  shockwaveDamage: 16,
} as const;

export const JUDGMENT_EYE_CONFIG = {
  texture: 'judgment-eye-placeholder',
  bulletTexture: 'judgment-eye-bullet-placeholder',
  maxHealth: 75,
  aggroRadius: 720,
  bodySize: 52,
  moveSpeed: 150,
  trackingDuration: 600,
  orbChargeDuration: 300,
  orbLifetime: 1_000,
  bulletSpeed: 220,
  bulletLifetime: 1_800,
  bulletDamage: 8,
  attackCooldown: 2_100,
  repositionDuration: 800,
} as const;
